import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import LayoutContainer from '@/components/LayoutContainer'
import ScrollToTopButton from '@/components/ScrollToTopButton'

const font = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Country Info App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${font.className} min-h-screen bg-white dark:bg-slate-900 text-slate-900 dark:text-white/90 overflow-x-hidden`}
      >
        <LayoutContainer>
          <Navbar />
          <div className="container mx-auto p-5">{children}</div>
          <ScrollToTopButton />
        </LayoutContainer>
      </body>
    </html>
  );
}
